#!/bin/bash

help() {
  echo "Usage:"
  echo "  install go"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro dvm install v1.32.1
}

run() {
  core $@
}

run $@
