#!/bin/bash

help() {
  echo "Usage:"
  echo "  install go"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro gvm install v1.20
}

run() {
  core $@
}

run $@
