#!/bin/bash

help() {
  echo "Usage:"
  echo "  install java"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # zulu 11
  export jdk_version=zulu@1.11.0

  zmicro jvm install $jdk_version

  zmicro package install maven
}

run() {
  core $@
}

run $@
