#!/bin/bash

help() {
  echo "Usage:"
  echo "  install node"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro nvm install v18.15.0

  # @TODO
  # npm: command not found
  # yarn: command not found
  #
  # source $HOME/.bashrc
  [ -s "$ZMICRO_HOME/plugins/nvm/source" ] && \. $ZMICRO_HOME/plugins/nvm/source

  # npm i -g npm@v9.5.0

  # @FEAT GPM (cli: gpm)
  npm i -g yarn @cliz/gpm @cliz/web-terminal @cliz/nobot @cliz/os-info

  npm -g config set prefix $HOME/.node

  yarn config set cache-folder $HOME/.node
}

run() {
  core $@
}

run $@
