#!/bin/bash

help() {
  echo "Usage:"
  echo "  install python"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro package install python
}

run() {
  core $@
}

run $@
