#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpipeline login docker [--registry <registry>] <username> <password>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local username=""
  local password=""
  local registry=""

  while [ "$#" -gt 0 ]; do
    case "$1" in
    --registry)
      registry="$2"
      shift
      shift
      ;;
    *)
      username="$1"
      password="$2"
      shift
      shift
      ;;
    esac
  done

  pipeline::docker_login "$username" "$password" "$registry"
}

run() {
  core $@
}

run $@
