#!/bin/bash

help() {
  echo "Usage:"
  echo "  pipeline build"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "################## Building ##################"
  pipeline::build
  log::info "################ Building END ################"
}

run() {
  core $@
}

run $@
