#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpipeline checkout"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "################## Checking out ##################"
  pipeline::checkout
  log::info "################ Checking out END ################"
}

run() {
  core $@
}

run $@
