#!/bin/bash

help() {
  echo "Usage:"
  echo "  pipeline checkout"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "################## CHECKOUT START ##################"

  pipeline::checkout
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to checkout"
    exit 1
  fi

  log::info "################ CHECKOUT END ################"
}

run() {
  core $@
}

run $@
