#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpipeline deploy"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::docker_deploy
}

run() {
  core $@
}

run $@
