#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpipeline deploy"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "################## DEPLOY START ##################"

  pipeline::deploy
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to deploy."
    exit 1
  fi

  log::info "################ DEPLOY END ################"
}

run() {
  core $@
}

run $@
