#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpipeline push [--registry <registry>] [--tags <tags>] <name> <context>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=""
  local context=""
  local tags=""
  local registry=""

  while [ "$#" -gt 0 ]; do
    case "$1" in
    --registry)
      shift
      registry="$1"
      shift
      ;;
    --tags)
      shift
      tags="$1"
      shift
      ;;
    *)
      name="$1"
      context="$2"
      shift
      shift
      ;;
    esac
  done

  log::info "################## Pushing ##################"
  docker::push "$name" "$context" "$tags" "$registry"
  log::info "################ Pushing END ################"
}

run() {
  core $@
}

run $@
