#!/bin/bash

help() {
  echo "Pipeline run fresh"
  echo ""
  echo "Usage:"
  echo "  zmicro pipeline run [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::prepare "$@"

  pipeline::run "$@"
}

run() {
  core "$@"
}

run "$@"
