#!/bin/bash

pipeline::build() {
  log::info "[$(os::timestamp)][pipeline][build] running ..."

  cd $PLUGIN_PIPELINE_DIR/config/compose

  if [ "$DEBUG" = "true" ]; then
    $DOCKER_COMPOSE config
    exit 0
  fi

  $DOCKER_COMPOSE build

  log::success "[$(os::timestamp)][pipeline][build] done."
}

export -f pipeline::build
