#!/bin/bash

pipeline::docker_login() {
  local username=$1
  local password=$2
  local registry=$3

  if [ "$username" = "" ]; then
    log::error "[pipeline::docker_login] username is required"
    exit 1
  fi

  if [ "$password" = "" ]; then
    log::error "[pipeline::docker_login] password is required"
    exit 1
  fi

  docker login $registry -u $username -p $password >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::error "Docker Login Failed"
    exit -1
  fi

  log::success "Docker Login Success"
}

export -f pipeline::docker_login
