#!/bin/bash

pipeline::service_stop() {
  log::info "[$(os::timestamp)][pipeline][service][stop] running ..."

  cd $PLUGIN_PIPELINE_DIR/config/compose

  if [ "$DEBUG" = "true" ]; then
    $DOCKER_COMPOSE config
    exit 0
  fi

  $DOCKER_COMPOSE down --remove-orphans

  log::success "[$(os::timestamp)][pipeline][service][stop] done."
}

export -f pipeline::service_stop
