#!/bin/bash

help() {
  echo "Pipeline service logs"
  echo ""
  echo "Usage:"
  echo "  zmicro pipeline service logs"
  echo ""
  echo "Environment variables:"
  echo "  PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME: The name of the pipeline service instance"
  echo "  PLUGIN_PIPELINE_SERVICE_IMAGE_NAME: The name of the pipeline service image"
  echo "  PLUGIN_PIPELINE_SERVICE_IMAGE_VERSION: The version of the pipeline service image"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::service_prepare

  pipeline::service_logs
}

run() {
  core "$@"
}

run "$@"
