#!/bin/bash

help() {
  echo "Pipeline service logs"
  echo ""
  echo "Usage:"
  echo "  zmicro pipeline service logs [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::service_prepare

  pipeline::service_logs "$@"
}

run() {
  core "$@"
}

run "$@"
