#!/bin/bash

help() {
  echo "Pipeline run fresh"
  echo ""
  echo "Usage:"
  echo "  zmicro pipeline service run [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::service_prepare "$@"

  pipeline::service_run "$@"
}

run() {
  core "$@"
}

run "$@"
