#!/bin/bash

help() {
  echo "Pipeline service start"
  echo ""
  echo "Usage:"
  echo "  zmicro pipeline service start [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  pipeline::prepare "$@"

  pipeline::start "$@"
}

run() {
  core "$@"
}

run "$@"
